name: Douban Top250 Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 执行 (UTC时间比北京时间晚8小时, 00:00 UTC 就是北京时间 08:00)
  workflow_dispatch:  # 允许手动触发

jobs:
  scrape:
    runs-on: ubuntu-latest  # 使用 Ubuntu 操作系统

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 检出仓库代码

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # 指定 Python 版本, 与你本地一致

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 zhconv  # 安装依赖

    - name: Run scraper
      run: python script/douban_scraper.py  # 运行你的 Python 脚本

    - name: Commit and push changes
      run: |
        git config --global user.name "xinn314"  # 替换为你的 GitHub 用户名
        git config --global user.email "xinn314@gmail.com"  # 替换为你的 GitHub 邮箱
        git add data/douban_top250/*.json  # 添加所有以 douban_top250_ 开头的 .json 文件
        timestamp=$(date +"%Y-%m-%d %H:%M:%S")
        git commit -m "Update Douban Top250 data ($timestamp)" || exit 0  # 提交更改, 如果没有更改则跳过
        git push
